#!/usr/bin/python -OO
#! /usr/bin/env python

import sys, os

prefix, bin = os.path.split(sys.path[0])

#print "prefix: ", prefix
#print "bin: ", bin
#print "sys.prefix: ", sys.prefix

#if bin == 'bin' and prefix != sys.prefix:
#    sys.prefix = prefix
#    sys.exec_prefix = prefix

from assurance.main import main

if __name__ == '__main__':
    main(sys.argv[1:])

#import profile
#if __name__ == '__main__':
#    profile.run('main(sys.argv[1:])', '/tmp/asure.profile')
